/* Auto-generated by genmsg_cpp for file /opt/planetxrobots/ros/RoverState/msg/Range.msg */
#ifndef ROVERSTATE_MESSAGE_RANGE_H
#define ROVERSTATE_MESSAGE_RANGE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace RoverState
{
template <class ContainerAllocator>
struct Range_ {
  typedef Range_<ContainerAllocator> Type;

  Range_()
  : header()
  , frontRangeCm(0)
  , backRangeCm(0)
  {
  }

  Range_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , frontRangeCm(0)
  , backRangeCm(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint16_t _frontRangeCm_type;
  uint16_t frontRangeCm;

  typedef uint16_t _backRangeCm_type;
  uint16_t backRangeCm;


  typedef boost::shared_ptr< ::RoverState::Range_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::RoverState::Range_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Range
typedef  ::RoverState::Range_<std::allocator<void> > Range;

typedef boost::shared_ptr< ::RoverState::Range> RangePtr;
typedef boost::shared_ptr< ::RoverState::Range const> RangeConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::RoverState::Range_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::RoverState::Range_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace RoverState

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::RoverState::Range_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::RoverState::Range_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::RoverState::Range_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b1976b1487c64c9b4693bb336701082a";
  }

  static const char* value(const  ::RoverState::Range_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb1976b1487c64c9bULL;
  static const uint64_t static_value2 = 0x4693bb336701082aULL;
};

template<class ContainerAllocator>
struct DataType< ::RoverState::Range_<ContainerAllocator> > {
  static const char* value() 
  {
    return "RoverState/Range";
  }

  static const char* value(const  ::RoverState::Range_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::RoverState::Range_<ContainerAllocator> > {
  static const char* value() 
  {
    return "#\n\
# front and read range measurements\n\
#\n\
Header header\n\
uint16 frontRangeCm\n\
uint16 backRangeCm\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::RoverState::Range_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::RoverState::Range_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::RoverState::Range_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::RoverState::Range_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.frontRangeCm);
    stream.next(m.backRangeCm);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Range_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::RoverState::Range_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::RoverState::Range_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "frontRangeCm: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.frontRangeCm);
    s << indent << "backRangeCm: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.backRangeCm);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROVERSTATE_MESSAGE_RANGE_H

